/* The Build a World aesthetic pool — every world with its visual language
   and a few cues. Mix of internet-era cores and the eras before them. */

export type Aesthetic = { n: string; d: string; c: string };

export const AESTHETICS: Aesthetic[] = [
  { n: "2012–2014 Tumblr", d: "Grainy photoset grids, faded film tones, and captions borrowed from poetry you'd never admit to liking.", c: "grainy photosets · faded film · lowercase captions · midnight blogging" },
  { n: "Fedora Swag", d: "2009-era cool-guy — plaid shirts, wayfarers, and a hat that means business. Earnest and a little embarrassing, in the best way.", c: "fedoras · wayfarers · plaid shirts · chest-fist poses" },
  { n: "Indie Sleaze", d: "Messy nightlife, flash photography, black leather — the last party before the internet got polite.", c: "flash photography · messy nightlife · black leather · blown-out highlights" },
  { n: "Scene", d: "Neon hair, skinny jeans, studded belts — maximalism with a side part and a glow-in-the-dark attitude.", c: "neon fringe · skinny jeans · studded belts · raccoon liner" },
  { n: "Emo", d: "Black-on-black layers, band tees, hair that hides half your face — feelings as fashion.", c: "band tees · side-swept fringe · studs & layers · moody lighting" },
  { n: "Soft Grunge", d: "Faded blacks, washed denim, flash photography, distressed textures — undone on purpose.", c: "faded blacks · washed denim · flash photography · distressed textures" },
  { n: "Cyber Sigilism", d: "Fine black linework crawling across skin and fabric — sacred geometry with a modem.", c: "black linework · sacred geometry · fine tattoos · chrome accents" },
  { n: "Coquette", d: "Ribbons, lace, bows, and blush — femininity dialed up until it's almost a costume.", c: "ribbons & bows · lace trim · pastel blush · girlish charm" },
  { n: "Gorpcore", d: "Technical shells, trail shorts, carabiners — the outdoors as a fashion statement.", c: "technical shells · trail shorts · carabiners · unbranded gear" },
  { n: "Old Money", d: "Quiet tailoring, tennis whites, a grandfather's watch — wealth that doesn't need to say it.", c: "tailored blazers · tennis whites · heritage watches · neutral knits" },
  { n: "Mob Wife", d: "Bold fur, big gold, dark sunglasses — glamour with an edge and a heavy accent.", c: "furs & gold · dark shades · leopard print · big energy" },
  { n: "Dark Feminine", d: "Deep florals, black lace, moonlight — softness with a bite.", c: "black lace · deep florals · velvet · candlelight" },
  { n: "Western Revival", d: "Cowboy boots, bolo ties, desert sunsets — the frontier, reissued.", c: "cowboy boots · bolo ties · fringe suede · desert tones" },
  { n: "90s Supermodel Minimalism", d: "Clean lines, slip dresses, slicked hair — beauty stripped to the bone.", c: "slip dresses · slicked-back hair · clean lines · editorial calm" },
  { n: "90s Hip-Hop", d: "Baggy denim, gold medallions, park-bench hangouts — culture with something to say.", c: "baggy denim · gold medallions · bucket hats · street-corner energy" },
  { n: "Bling Era", d: "2000s ice, oversized chains, diamond-encrusted everything — loud, proud, undeniable.", c: "oversized chains · diamond charm · fur coats · flashbulbs" },
  { n: "Quiet Luxury", d: "Cashmere, camel, unmarked logos — the flex is that you don't need one.", c: "cashmere · camel tones · unmarked logos · whispered wealth" },
  { n: "Streetwear", d: "Oversized silhouettes, limited drops, logo games — the uniform of the fast and the cultish.", c: "oversized silhouettes · logo prints · limited drops · skate energy" },
  { n: "Downtown Creative", d: "Black turtlenecks, gallery mumbles, effortless mess — art-school cool for the city after dark.", c: "black turtlenecks · gallery openings · studio mess · effortless cool" },
  { n: "2000s Movie Core", d: "Rom-com lighting, city nights, flip phones, soft flash, warm interiors, glossy magazines — early-digital nostalgia, grainy yet polished.", c: "rom-com lighting · flip phones · soft flash · grainy yet polished" },
  { n: "Belle Époque Paris", d: "Gaslight, absinthe, silk and scandal — the city of light before the war.", c: "gaslight glow · silk gowns · absinthe greens · café society" },
  { n: "Art Nouveau", d: "Whiplash curves, botanical linework, women with flowing hair — nature drawn like breath.", c: "whiplash curves · botanical linework · stained glass · flowing hair" },
  { n: "Art Deco", d: "Sweeping gold geometry, lacquer and marble — the twenties drawn in straight lines.", c: "gold geometry · lacquer · fan motifs · stepped skylines" },
  { n: "Jazz Age", d: "Fringe, feathers, cigarettes and champagne — America dancing faster than it could think.", c: "fringe & feathers · champagne · saxophone smoke · bobbed hair" },
  { n: "Harlem Renaissance", d: "Brownstones, jazz clubs, poets and stride piano — a culture declaring itself in public.", c: "brownstone stoops · jazz clubs · fedoras & zoot suits · poetry on stage" },
  { n: "1920s Speakeasy", d: "Password doors, dim brass, bathtub gin — the party that had to hide made it sweeter.", c: "dim brass · hidden doors · bathtub gin · velvet booths" },
  { n: "1930s Hollywood Glamour", d: "Silver screens, satin gowns, studio lights — fame when it still felt like magic.", c: "satín gowns · studio lights · platinum curls · red carpet flash" },
  { n: "Old Hollywood Studio Portraiture", d: "Rembrandt lighting, bermuda collars, painted perfection — faces made to sell dreams.", c: "Rembrandt lighting · painted perfection · high-key glamour · 8x10 glossies" },
  { n: "Film Noir", d: "Venetian blinds, wet streets, smoking guns — everybody lies in black and white.", c: "venetian blinds · wet asphalt · cigarette smoke · chiaroscuro shadows" },
  { n: "1940s Wartime Utility", d: "Make-do-and-mend, victory gardens, sharp shoulders — beauty under rationing.", c: "victory gardens · ration-book chic · sharp shoulders · knit & wool" },
  { n: "1940s Pin-Up", d: "Rosie cheeks, victory rolls, sailor stripes — smoldering with wholesome cover art.", c: "victory rolls · polka dots · sailor stripes · red lips" },
  { n: "1950s Diner Americana", d: "Chrome counters, cherry cokes, jukebox neon — small-town America at its shiniest.", c: "chrome counters · checkered tile · jukebox neon · cherry red" },
  { n: "Mid-Century Modern", d: "Teak, sunburst clocks, kidney-shaped everything — optimism with clean edges.", c: "teak & walnut · sunburst clocks · kidney shapes · atomic prints" },
  { n: "1950s Italian Cinema", d: "Neorealist streets, espresso, tailoring — beauty in the everyday drama.", c: "piazza light · espresso bars · soft tailoring · Vespa dust" },
  { n: "La Dolce Vita", d: "Via Veneto, sunglasses at night, paparazzi — sweetness and weariness in one frame.", c: "paparazzi flash · night sunglasses · white linen · ruins & scooters" },
  { n: "French New Wave", d: "Jump cuts, hand-held streets, existential chatter — cinema that broke its own rules.", c: "jump cuts · handheld streets · striped boatnecks · existential talk" },
  { n: "1960s Mod London", d: "Mini skirts, op-art, scooters and pills of color — the city remade by the young.", c: "minis & op-art · scooter traffic · geometric prints · Carnaby color" },
  { n: "Space Age Futurism", d: "White vinyl, googie curves, chrome rockets — the future as a clean room.", c: "white vinyl · googie curves · chrome rockets · astronaut helmets" },
  { n: "1960s Psychedelic", d: "Liquid color, melting letterforms, light shows — perception with the lid off.", c: "liquid color · melting type · light shows · kaleidoscope washes" },
  { n: "Swinging Sixties", d: "Twiggy lashes, black-and-white pop, go-go boots — the decade hitting its stride.", c: "go-go boots · Twiggy lashes · mod mini silhouettes · pop color" },
  { n: "1970s Disco", d: "Mirrorballs, platform soles, polyester shine — dancing until the lights came up.", c: "mirrorballs · platforms · polyester shine · Saturday strobe" },
  { n: "Studio 54", d: "Velvet ropes, celebrity glitter, one perfect night on repeat — the club as myth.", c: "velvet ropes · champagne towers · glitter dust · strobe silhouettes" },
  { n: "1970s Soul", d: "Afros, three-piece suits, smoky ballads — music with gravity and gold chains.", c: "three-piece suits · gold chains · afro pride · smoky ballad light" },
  { n: "1970s Funk", d: "Big collars, bushy brows, heavyweight basslines — rhythm you can wear.", c: "big collars · afro picks · bassline swagger · earth tones" },
  { n: "1970s Bohemian", d: "Suede vests, macrame, van life, joint-lit sunsets — freedom as a wardrobe.", c: "suede & macrame · van life · round shades · harvest gold" },
  { n: "1970s Rock Tour", d: "Backstage passes, road cases, stadium haze — the road as a shared hallucination.", c: "backstage passes · road cases · stadium haze · denim & leather" },
  { n: "1980s Wall Street", d: "Power suits, suspenders, marble lobbies — money as a contact sport.", c: "power suits · suspenders · marble lobbies · landline swagger" },
  { n: "1980s Power Glamour", d: "Shoulder pads, big hair, gold buttons — success with a soundtrack.", c: "shoulder pads · big hair · gold buttons · hair-metal sheen" },
  { n: "1980s Memphis Design", d: "Bold squiggles, pastel triangles, radical typography — furniture that refused to sit still.", c: "bousy squiggles · pastel triangles · laminate patterns · radical type" },
  { n: "1980s Aerobics", d: "Neon legwarmers, leotards, bandanas — fitness as neon theater.", c: "neon legwarmers · leotards · sweatbands · gym-floor gloss" },
  { n: "1980s Miami Nightlife", d: "Pastel hotel neon, convertible nights, vice-lit palms — the coast after dark.", c: "pastel neon · convertible chrome · palm silhouettes · vice-lit blues" },
  { n: "1990s Rave Culture", d: "Smiley faces, whistle blasts, warehouse dawns — the underground as a weekend religion.", c: "smiley badges · whistles · warehouse strobes · 5am fields" },
  { n: "1990s House Music", d: "Swept floors, drum loops, deep basements — repetition that becomes transcendence.", c: "drum loops · basement sweat · record crates · hands-up breaks" },
  { n: "1990s New York Street Style", d: "Oversized layers, subway light, corner crews — the city dressed by the streets.", c: "oversized layers · subway glow · fitted caps · stoop sessions" },
  { n: "1990s Hip-Hop Editorial", d: "Timberlands with tailoring, gold teeth close-ups, studio flash — rap dressed for the magazine.", c: "timberland tailoring · gold-tooth flashes · studio glare · puffa silhouettes" },
  { n: "1990s Supermodel Era", d: "Slip dresses, backstage chaos, paparazzi night — beauty as a public event.", c: "slip dresses · backstage flash · big sunglasses · waiting-room chaos" },
  { n: "Victorian Mourning", d: "Jet beads, black veils, pressed flowers — grief with a full dress code.", c: "jet beads · black veils · pressed flowers · sepia silence" },
  { n: "Victorian Botanical", d: "Pressed ferns, herbarium plates, terrarium glass — nature pinned and adored.", c: "herbarium plates · fern fronds · terrarium glass · muted greens" },
  { n: "Edwardian Romance", d: "Lace parasols, lawn tennis, white linen — courtship in long, lovely summers.", c: "lace parasols · lawn tennis · white linen · garden light" },
  { n: "Regency Elegance", d: "Empire waists, library candles, poetry on the chaise — manners as armor.", c: "empire waists · candlelight libraries · dance cards · pale silk" },
  { n: "Rococo", d: "Gilt swirls, powder pink, shepherdess dreams — ornament with nothing to prove.", c: "gilt swirls · powder pink · shell motifs · courtly excess" },
  { n: "Baroque Opulence", d: "Heavy gold, dramatic chiaroscuro, velvets and marble — grandeur that demands a gasp.", c: "heavy gold · dramatic shadows · velvet & marble · ceiling frescoes" },
  { n: "Renaissance Portraiture", d: "Sfumato faces, velvet sleeves, northern light — likeness as a form of worship.", c: "sfumato glow · velvet sleeves · northern light · pearl detail" },
  { n: "Medieval Illuminated Manuscript", d: "Gold leaf margins, painted initials, slow ink — words treated like sacred objects.", c: "gold leaf · painted initials · vellum warmth · marginalia beasts" },
  { n: "Gothic Cathedral", d: "Rose windows, flying buttresses, candlelit stone — faith built to touch the sky.", c: "rose windows · stone ribbing · candlelight · vaulted gloom" },
  { n: "Ancient Roman Fresco", d: "Pompeian reds, painted gardens, villa courtyards — daily life staged in pigment.", c: "Pompeian red · painted gardens · marble veins · laurel wreaths" },
  { n: "Ancient Egyptian Revival", d: "Lapis and gold, scarabs, columned temples — eternity drawn in profile.", c: "lapis & gold · scarab motifs · temple columns · profile lines" },
  { n: "Edo-Period Japanese Printmaking", d: "Ukiyo-e waves, indigo skies, woodgrain lines — a world pressed into paper.", c: "ukiyo-e waves · indigo skies · woodgrain line · kimono silhouettes" },
  { n: "Shanghai Art Deco", d: "Jade tones, brass details, Bund skyline nights — East and West dancing in chrome.", c: "jade & brass · Bund skyline · cheongsam lines · neon calligraphy" },
  { n: "1960s–70s Hong Kong Cinema", d: "Neon alleyways, rain-slick streets, matinee shadows — Wuxia, noir and hustle.", c: "neon alleys · rain-slick streets · bamboo scaffolding · matinee shadows" },
  { n: "Fairy Grunge", d: "Moth wings, tarnished silver, nettle skirts — the forest floor, moody and soft.", c: "moth wings · tarnished silver · nettle textures · dusky moss" },
  { n: "Whimsigoth", d: "Amulets, velvet, moon phases, midnight purple — mystic with a bohemian accent.", c: "velvet & amulets · moon phases · midnight purple · incense haze" },
  { n: "Whimsicore", d: "Mushrooms, lanterns, cottage dust, storybook light — childhood wonder, adult hands.", c: "mushroom caps · lantern glow · storybook edges · soft moss beds" },
  { n: "Whimsicore Maximalism", d: "Every shelf full, every color warm — wonder with no empty corners.", c: "packed shelves · layered textures · warm overload · curio chaos" },
  { n: "Medieval Revival", d: "Tapestries, tankards, chainmail evenings — the old world cosplayed with love.", c: "tapestry walls · tankard clay · chainmail glint · candle feasts" },
  { n: "Medieval Fantasy", d: "Castles at dusk, capes in wind, quests unspoken — fantasy as an aesthetic default.", c: "castle silhouettes · cloak wind · torchlight · ancient woods" },
  { n: "Renaissance Romantic", d: "Oil portraits, allegory gardens, sonnet ink — old-master feeling for a new crush.", c: "oil portrait light · allegory gardens · sonnet paper · clasps & pearls" },
  { n: "Dark Romanticism", d: "Storm moors, obsession letters, candlewax — romance with gothic weather.", c: "storm moors · candlewax · letter seals · brooding skies" },
  { n: "Occult Editorial", d: "Crystal balls, tarot spreads, altar candles — mysticism shot like a magazine.", c: "crystal spheres · tarot spreads · altar candles · incense rot" },
  { n: "Witchy Minimalism", d: "Black jars, single candles, salt lines — a practice stripped to essentials.", c: "black jars · single flames · salt lines · quiet shadows" },
  { n: "Cosmic Mysticism", d: "Nebula washes, sacred geometry, star charts — the universe as a votive.", c: "nebula washes · sacred geometry · star charts · void velvet" },
  { n: "Celestial Romance", d: "Moon phases, silver thread, midnight blue — lovers under astrological light.", c: "moon phases · silver thread · midnight blue · constellation lace" },
  { n: "Sun Worship", d: "Amber glare, desert heat, gold hour everything — devotion to the light source.", c: "amber glare · gold hour · baked earth · halo silhouettes" },
  { n: "Desert Mystic", d: "Dunes at dusk, dusty veils, lone fires — silence with a heartbeat.", c: "dune lines · dusty veils · lone fires · heat shimmer" },
  { n: "Oracle Aesthetic", d: "Dice, runes, worn cards, candle-stained cloth — messages from the old deck.", c: "worn cards · rune stones · candle-stained cloth · silver pendulums" },
  { n: "Tarot Noir", d: "Smoke, mirrors, shadow arcana — the Major Arcana dressed in film grain.", c: "cigarette smoke · cracked cards · venetian shadows · noir moons" },
  { n: "Neo-Western", d: "Raw denim, rodeo dust, tumbleweed minimalism — the frontier re-shot in 4K.", c: "raw denim · rodeo dust · steel horses · dry brush gold" },
  { n: "Rodeo Glam", d: "Satin shirts, belt buckles, arena lights — the showiness of the showground.", c: "satin shirts · buckle shine · arena lights · barrel-race flair" },
  { n: "Prairie Romantic", d: "Gingham, wildflowers, wide-sky light — homestead feeling, softened.", c: "gingham checks · wildflower stems · prairie wind · linen dust" },
  { n: "Ranch Luxe", d: "Leather, brass, stone fireplaces — the ranch as a five-star idea.", c: "tooled leather · brass fittings · stone hearths · morning mist" },
  { n: "Coastal Prep", d: "Nantucket reds, boat shoes, dock light — the shore as a lifestyle brand.", c: "Nantucket red · boat shoes · sailcloth stripes · harbor blue" },
  { n: "New England Summer", d: "Clapboard whites, hydrangea blues, lobster-roll light — one perfect season.", c: "clapboard white · hydrangea blue · lobster-roll light · porch evenings" },
  { n: "Fisherman Aesthetic", d: "Waxed canvas, harbor rope, cold-water grays — the sea done honestly.", c: "waxed canvas · harbor rope · cold-water gray · trawler rust" },
  { n: "Nautical Vintage", d: "Skipper stripes, brass compasses, chart paper — the sea as nostalgia.", c: "skipper stripes · brass compass · chart paper · harbor fog" },
  { n: "Seaside Motel", d: "Pastel doors, pool mosaics, neon vacancy — the coast at its palm-spangled sleepiest.", c: "pastel doors · pool mosaics · neon vacancy · salt air" },
  { n: "Palm Springs Retro", d: "Butter-yellow mid-century, poolside geometry, desert afternoons — the easy side of modernism.", c: "butter yellow · pool geometry · bougainvillea · diptych doors" },
  { n: "Miami Vice", d: "Pastel linen, night ocean, synthwave sunsets — the eighties coast at full boil.", c: "pastel linen · night ocean · synthwave sunset · sailboat lines" },
  { n: "Vegas Kitsch", d: "Neon signatures, carpet patterns, lounge velvet — delight with the volume up.", c: "neon signatures · casino carpet · lounge velvet · showroom glow" },
  { n: "Casino Glamour", d: "Green felt, gold railings, roulette spin — luck dressed for dinner.", c: "green felt · gold railings · roulette spin · champagne flutes" },
  { n: "Palm Beach Prep", d: "Pastel pants, brass buttons, wrapped in sunlight — old-money leisure, louder colors.", c: "pastel trousers · brass buttons · sun spills · croquet lawns" },
  { n: "Country Club", d: "Creased khakis, green fairways, clubhouse light — belonging as a uniform.", c: "creased khakis · fairway green · clubhouse glow · quiet luxury jokes" },
  { n: "Preppy Sport", d: "Collars popped, varsity stripes, match-day energy — sport as a full-time look.", c: "popped collars · varsity stripes · tote bags · match-day light" },
  { n: "Tennis Club Vintage", d: "Cream knits, wood rackets, clay dust — the gentlest athletic aesthetic.", c: "cream knits · wood rackets · clay dust · white-line geometry" },
  { n: "Equestrian Heritage", d: "Tweed, leather, stable brass — the horse world's quiet codes.", c: "tweed & leather · stable brass · hacking jackets · morning frost" },
  { n: "Safari Luxe", d: "Khaki tailoring, canvas trunks, dust-filtered light — the expedition, first class.", c: "khaki tailoring · canvas trunks · dust-filtered light · field binoculars" },
  { n: "Expeditioncore", d: "Crampons, carabiners, base-camp layers — the trip itself as the uniform.", c: "crampon steel · carabiner rings · base-camp layers · summit cold" },
  { n: "Mountain Lodge", d: "Timber beams, plaid blankets, firelight — the cabin as warm headquarters.", c: "timber beams · plaid wool · firelight · window snow" },
  { n: "Alpine Minimalism", d: "Clean slopes, raw concrete and oak — the mountain drawn with a ruler.", c: "clean slopes · oak & concrete · high-altitude light · simple lines" },
  { n: "Cabin Modern", d: "Black windows, cedar warmth, forest floor views — architecture leaning into the woods.", c: "black frames · cedar warmth · forest light · poured concrete" },
  { n: "Forest Luxe", d: "Velvet moss, gold fall light, deep quiet — the woods as a hotel lobby.", c: "velvet moss · gold light · deep quiet · canopy shadows" },
  { n: "Dark Forest", d: "Root caves, fog seams, wolf-hour light — the woods past sundown.", c: "root caves · fog seams · wolf-hour light · undergrowth dark" },
  { n: "Mossy Romantic", d: "Green velvet, stone steps, rain-wet leaves — tenderness with a forest floor.", c: "green velvet · stone steps · rain-wet leaves · muted fern" },
  { n: "Garden Party", d: "Linens, peonies, long tables — the afternoon as an invitation.", c: "white linens · peony heads · long tables · champagne light" },
  { n: "Floral Maximalism", d: "Layer after layer of bloom, pattern on pattern — the garden, indoors and loud.", c: "bloom layers · pattern mixing · hothouse color · petal density" },
  { n: "English Garden", d: "Yew hedges, wildflower edges, stone path light — order that learned to relax.", c: "yew hedges · wildflower edges · stone paths · soft gray-rose" },
  { n: "Greenhouse Editorial", d: "Glass panels, propagation trays, rain-country light — plants shot like fashion.", c: "glass panels · propagation trays · damp light · leaf shadows" },
  { n: "Farmer's Market Chic", d: "Canvas totes, heirloom stems, early-morning crates — the produce aisle at its prettiest.", c: "canvas totes · heirloom stems · morning crates · dirt-and-dew" },
  { n: "Organic Grocery", d: "Brown paper, bulk bins, wheatgrass green — food shopping as a wellness ritual.", c: "brown paper · bulk bins · wheatgrass green · chalkboard type" },
  { n: "Natural Wine Bar", d: "Orange wines, candlelit glass, label scribbles — drinking as design appreciation.", c: "orange wine · candle glass · scribbled labels · terracotta walls" },
  { n: "Café Society", d: "Espresso steam, marble counters, literati hush — the café as a second home.", c: "espresso steam · marble counters · newspaper light · seated gossip" },
  { n: "Space Age Afterglow", d: "Console buttons, brushed metal, recorder bleeps — the future, slightly dated and loved.", c: "console buttons · brushed metal · bleeping scales · convex screens" },
  { n: "Hong Kong Cinema", d: "Neon rain, rooftop chases, bruised romantics — every frame lit like a city that never sleeps.", c: "neon signs · rain-slick streets · wide-brim shadows · wire work" },
];