import type { HelpCfg } from "./help-kit";

const CALL = { when: "Day 1", t: "Free call", d: "15 to 30 minutes. You tell me what you need, I ask the questions." };
const PLAN = { when: "Right after", t: "Plan + price", d: "You get a plan, a timeline and one clear price. Nothing starts until you say yes." };

export const BRANDING: HelpCfg = {
  reel: "A 30 second reel of brands I've built",
  get: [
    { t: "Logo + every version", d: "Main logo, small mark, light and dark." },
    { t: "Colors + fonts", d: "A short palette and type you can use anywhere." },
    { t: "Your voice", d: "How the brand talks, from bio to captions." },
    { t: "A brand guide", d: "One simple guide so everything stays consistent." },
    { t: "Files, organized", d: "All of it in Google Drive or Dropbox, labeled." },
    { t: "Help using it", d: "A walkthrough so you know where everything goes." },
  ],
  work: [
    { t: "Jazmin's Events", w: "Brand guide · in progress", img: "/assets/campaigns/jazmins-events/kit-guide.jpg", h: "/websites/jazmins-events" },
    { t: "Essential Brows", w: "Brand kit", img: "/assets/campaigns/essential-brows-studio/brand-kit.jpg", h: "/websites/essential-brows-studio" },
    { t: "Pilates Haus", w: "Brand kit + website", img: "/assets/campaigns/pilates-haus-cover.png", h: "https://pilates-haus-seattle.vercel.app/" },
  ],
  need: "Branding",
  noun: "Branding",
  videos: [
    { t: "60 seconds: what a brand actually is", d: "It's more than a logo. The short version." },
    { t: "A brand world, from moodboard to final", d: "Watch one come together, start to finish." },
    { t: "What our first call is like", d: "So you know exactly what to expect." },
  ],
  forWho: [
    { t: "Starting something new", d: "You have the idea and the name, but no look yet." },
    { t: "Your look doesn't match you anymore", d: "The business grew up. The logo and colors didn't." },
    { t: "Everything looks different everywhere", d: "Your sign, site and Instagram feel like three businesses." },
  ],
  gallery: [
    { label: "A full brand guide, laid out page by page" },
    { label: "Logo on a storefront or sign" },
    { label: "Business cards and packaging" },
    { label: "A brand world coming together", kind: "video" },
  ],
  quoteWho: "Jazmin, Jazmin's Events",
  madeImg: "/assets/work/hana-desk-bio.jpg",
  madeTitle: "One person, from the moodboard to the last post.",
  madeP: "I build the brand and can make everything after it too: the site, the photos and the content. So it all looks like it came from the same place, because it did.",
  bts: ["Moodboards spread out on the desk", "Sketching the first logo ideas", "Picking colors with a client"],
  timeline: [CALL, PLAN, { when: "Next", t: "Direction", d: "References and a moodboard, so we agree on the feeling before anything is designed." }, { when: "Then", t: "Design + refine", d: "Logo, colors, type and voice, refined together until it feels like you." }, { when: "Handoff", t: "Your brand kit", d: "All your files and a simple guide, organized in Google Drive or Dropbox." }],
  estTitle: "What would my brand cost?",
  base: [
    { id: "logo", t: "Logo", d: "A mark that works everywhere", p: 350, plus: true },
    { id: "kit", t: "Brand kit", d: "Keep your logo, get colors, type and a guide", p: 550, plus: true },
    { id: "world", t: "Full brand world", d: "Strategy, identity, voice and a full guide", p: 1500, plus: true },
  ],
  extras: [
    { id: "canva", t: "Canva template pack", d: "Your brand set up in Canva + 15 templates", p: 300, plus: true },
    { id: "shoot", t: "Brand photos", d: "Half day, 30+ edited photos", p: 550, plus: true },
    { id: "site", t: "A website for it", d: "4 to 5 pages, booking or inquiries", p: 850 },
    { id: "print", t: "Print kit", d: "A menu, an A-frame and two signs", p: 400, plus: true },
  ],
  prep: [
    { t: "Your business name", d: "And how you want it written." },
    { t: "Who your customers are", d: "A few words is enough. We'll dig in together." },
    { t: "3 to 5 brands you love", d: "Any industry. Screenshots are perfect." },
    { t: "Anything you already have", d: "Old logo, colors, fonts, even ones you don't like." },
    { t: "Words that describe the feeling", d: "Calm, bold, playful, luxe. Whatever comes to mind." },
    { t: "What you never want to look like", d: "Just as useful as what you do want." },
  ],
  guideTitle: "What every small business brand needs.",
  guide: [
    { t: "A logo that works small", d: "It has to read on a phone screen, a stamp and a sign. Simple usually wins.", slot: "One logo shown big, small and on a phone" },
    { t: "Two or three colors", d: "A short palette people start to recognize, used the same way every time.", slot: "A color palette with real uses" },
    { t: "One or two fonts", d: "One for headlines, one for everything else. That's it.", slot: "Headline and body fonts side by side" },
    { t: "A voice", d: "How you talk in captions, emails and signs. Warm, direct, playful, whatever is true.", slot: "The same caption in two different voices" },
    { t: "Photos that match", d: "Your photos should feel like the brand, not like stock.", slot: "A brand palette next to matching photos" },
    { t: "A simple guide", d: "One place that says how it all gets used, so anyone helping you keeps it consistent.", slot: "Pages from a brand guide" },
  ],
  words: [
    { w: "Brand", d: "The whole feeling people get from your business, not just the logo." },
    { w: "Identity", d: "The visual parts: logo, colors, fonts and how they're used." },
    { w: "Brand kit", d: "The files you need to use your brand anywhere." },
    { w: "Brand guide", d: "A short document that shows how to use it all." },
    { w: "Wordmark", d: "A logo made from the name, in a special font." },
    { w: "Mark / icon", d: "A small symbol that can stand on its own." },
    { w: "Moodboard", d: "A collage of references that shows the feeling we're going for." },
    { w: "Palette", d: "The set of colors your brand uses." },
  ],
};

export const LOGO: HelpCfg = {
  ...BRANDING,
  reel: "A 30 second reel of logos, sketch to final",
  get: [
    { t: "Main logo", d: "The full version, for signs and your site." },
    { t: "Small mark", d: "For profile pictures, stamps and favicons." },
    { t: "Light + dark", d: "Versions that work on any background." },
    { t: "Every file type", d: "PNG, SVG and PDF, labeled so you can find them." },
  ],
  work: [
    { t: "Jazmin's Events", w: "Monogram + wordmark", img: "/assets/campaigns/jazmins-events/je-monogram-black.svg", h: "/websites/jazmins-events" },
    { t: "Essential Brows", w: "Wordmark", img: "/assets/work/essential-logo.png", h: "/websites/essential-brows-studio" },
    { t: "Pilates Haus", w: "Brand kit around their logo", img: "/assets/campaigns/pilates-haus-cover.png", h: "https://pilates-haus-seattle.vercel.app/" },
  ],
  need: "Logo / Identity",
  noun: "Logo",
  videos: [
    { t: "60 seconds: what makes a good logo", d: "Simple, clear and works everywhere." },
    { t: "One logo from sketch to final", d: "Every version, in under a minute." },
    { t: "Testing a logo in the real world", d: "On a sign, a cup and a phone." },
  ],
  forWho: [
    { t: "No logo yet", d: "You're using your name in a default font, or nothing at all." },
    { t: "A DIY logo you've outgrown", d: "It got you started. Now it's holding you back." },
    { t: "A logo that breaks when it's small", d: "Too detailed for a profile picture or a stamp." },
  ],
  gallery: [
    { label: "A logo sheet with every version" },
    { label: "Logo on a coffee cup or bag" },
    { label: "Logo as an Instagram profile picture" },
    { label: "A logo drawn from sketch to final", kind: "video" },
  ],
  quoteWho: "a logo client",
  madeTitle: "Every logo starts on paper.",
  madeP: "I sketch first, then refine on screen, then test it everywhere it will live: your sign, your site and your phone. You see the process, not just the final file.",
  bts: ["Pages of early logo sketches", "Testing the logo on real things", "Final files being organized"],
  timeline: [CALL, PLAN, { when: "Next", t: "Sketches", d: "A few directions on paper, so you can react before anything is polished." }, { when: "Then", t: "Refine", d: "One direction, refined together, tested small and big." }, { when: "Handoff", t: "Your files", d: "Every version and format you need, organized and labeled." }],
  estTitle: "What would my logo cost?",
  base: [
    { id: "logo", t: "Logo", d: "A mark that works everywhere", p: 350, plus: true },
    { id: "kit", t: "Logo + brand kit", d: "Colors, type and a short guide too", p: 550, plus: true },
  ],
  extras: [
    { id: "canva", t: "Canva template pack", d: "Your brand set up in Canva + 15 templates", p: 300, plus: true },
    { id: "site", t: "A website for it", d: "4 to 5 pages, booking or inquiries", p: 850 },
  ],
  guideTitle: "What makes a logo work.",
  guide: [
    { t: "It reads in one second", d: "If people have to squint, it's too busy.", slot: "A logo glimpsed for one second" },
    { t: "It works in one color", d: "Black, white, on a photo. A good logo survives all of them.", slot: "One logo in black, white and on a photo" },
    { t: "It has a small version", d: "A short mark or icon for profile pictures and favicons.", slot: "Full logo next to its small icon" },
    { t: "It fits your customers", d: "Not trendy for its own sake. Right for who you serve.", slot: "Two logos for the same business, two audiences" },
    { t: "You get the right files", d: "PNG, SVG, PDF, light and dark. Labeled so you can find them.", slot: "A tidy folder of logo files" },
  ],
};

export const PHOTO: HelpCfg = {
  reel: "A 30 second reel of shoots",
  need: "Photography",
  noun: "Photography",
  videos: [
    { t: "60 seconds: why real photos beat stock", d: "The short version, for anyone on the fence." },
    { t: "Behind the scenes of a brand shoot", d: "What a half day with me actually looks like." },
    { t: "How to get ready for your shoot", d: "Outfits, the space, what to bring." },
  ],
  forWho: [
    { t: "Photos that don't look like you", d: "Old, blurry, stock, or taken on the fly." },
    { t: "Opening or relaunching", d: "You need a full set for the site, menu or feed." },
    { t: "Something worth remembering", d: "An event, a launch or an artist moment." },
  ],
  gallery: [
    { label: "A portrait from a brand shoot" },
    { label: "Product or food, styled" },
    { label: "Your space, shot wide" },
    { label: "Behind the scenes of a shoot", kind: "video" },
  ],
  quoteWho: "a photo client",
  madeImg: "/assets/work/hero-hana-01.jpg",
  madeTitle: "I direct, so you don't have to pose.",
  madeP: "Most people say they hate being photographed. I plan the shot list, set up the light and talk you through every frame, so you just get to be yourself.",
  bts: ["Setting up lights before a shoot", "Directing a client on set", "Picking the best frames together"],
  timeline: [CALL, PLAN, { when: "Before", t: "Shot list", d: "What we need, where and when. You'll know exactly what to wear and bring." }, { when: "Shoot day", t: "The shoot", d: "Relaxed and directed. Half a day covers most brand shoots." }, { when: "After", t: "Your gallery", d: "Edited photos in an online gallery, ready to post and download." }],
  estTitle: "What would my shoot cost?",
  base: [
    { id: "head", t: "Headshot", d: "One look, one finished photo", p: 150 },
    { id: "brand", t: "Brand shoot", d: "Half day, 30+ edited photos", p: 550, plus: true },
    { id: "event", t: "Event coverage", d: "2 hours, $150 an hour after that", p: 300, plus: true },
  ],
  extras: [
    { id: "dir", t: "Creative direction", d: "Concept, moodboard and styling for your shoot", p: 200 },
    { id: "phone", t: "Phone content day", d: "Short videos for Reels and TikTok", p: 350 },
    { id: "canva", t: "Canva template pack", d: "Templates to post your photos in", p: 300, plus: true },
    { id: "site", t: "A website to put them on", d: "4 to 5 pages, booking or inquiries", p: 850 },
  ],
  prep: [
    { t: "What the photos are for", d: "Website, menu, Instagram, press. It changes the shot list." },
    { t: "2 or 3 outfits", d: "Solid colors photograph best. I'll help you choose." },
    { t: "Your space, tidied", d: "Clear counters and surfaces. I'll handle the rest." },
    { t: "Products or dishes ready", d: "Your best-looking ones, plus a few spares." },
    { t: "Photos you love", d: "From anyone. Screenshots are perfect." },
    { t: "Who's in the photos", d: "Just you, your team or your customers." },
  ],
  guideTitle: "What makes a brand photo work.",
  guide: [
    { t: "Real people", d: "Your face and your team build more trust than any stock photo.", slot: "A real owner portrait vs. a stock photo" },
    { t: "Good light", d: "Soft, natural light flatters everyone and everything.", slot: "The same shot in harsh vs. soft light" },
    { t: "A consistent look", d: "Same feel across every photo, so your feed and site match.", slot: "A grid of photos that all feel the same" },
    { t: "Detail shots", d: "Hands, textures and close-ups make a set feel complete.", slot: "Three detail shots from one shoot" },
    { t: "Space to add text", d: "Some wide shots with room for headlines on your site.", slot: "A photo with a headline over it" },
    { t: "Vertical and horizontal", d: "Vertical for phones and stories, horizontal for websites.", slot: "The same moment, vertical and horizontal" },
  ],
  words: [
    { w: "Shot list", d: "The list of photos we need, planned before the shoot." },
    { w: "Gallery", d: "An online folder where you view and download your photos." },
    { w: "Editing", d: "Color, light and cleanup on each finished photo." },
    { w: "Retouching", d: "Detailed touch-ups, like skin or stray hairs." },
    { w: "Usage", d: "Where you're allowed to use the photos. For brand shoots, that's your own channels." },
    { w: "Golden hour", d: "The soft light just after sunrise or before sunset." },
    { w: "Flat lay", d: "Products arranged and shot from above." },
    { w: "BTS", d: "Behind the scenes. Great for social posts." },
  ],
};

export const HEADSHOTS: HelpCfg = {
  ...PHOTO,
  reel: "A 30 second reel of headshot sessions",
  get: [
    { t: "A directed session", d: "I guide every pose, so you don't have to think." },
    { t: "See them as we go", d: "We check the photos together on camera." },
    { t: "Finished, edited photos", d: "Color and light done, ready to post." },
    { t: "Sized for where they go", d: "Square for profiles, wider for your site." },
    { t: "An online gallery", d: "View, pick and download from anywhere." },
  ],
  need: "Headshots",
  noun: "Headshot",
  videos: [
    { t: "60 seconds: what makes a headshot good", d: "Light, angle and a real smile." },
    { t: "A headshot session, start to finish", d: "Quick, easy and directed." },
    { t: "What to wear for headshots", d: "Colors, necklines and what to skip." },
  ],
  forWho: [
    { t: "Your photo is a selfie", d: "Or cropped from a wedding, years ago." },
    { t: "A new job or a new business", d: "LinkedIn, your website and press all need one." },
    { t: "A whole team", d: "Everyone matching, in one easy session." },
  ],
  gallery: [
    { label: "A clean studio headshot" },
    { label: "An outdoor, natural light headshot" },
    { label: "A team, all matching" },
    { label: "A session in 30 seconds", kind: "video" },
  ],
  quoteWho: "a headshot client",
  madeTitle: "Nervous? That's normal.",
  madeP: "Almost everyone is. I talk you through it, show you the photos as we go and keep it quick. Most people leave saying it was easier than they thought.",
  bts: ["Checking the photos together on camera", "A quick outfit change", "The finished headshot on LinkedIn"],
  timeline: [CALL, { when: "Before", t: "Pick a look", d: "Studio or outdoor, and what to wear. I'll send tips." }, { when: "Session", t: "The shoot", d: "Short and directed. We look at photos together as we go." }, { when: "After", t: "You choose", d: "Pick your favorites from the gallery." }, { when: "Done", t: "Finished photos", d: "Edited and ready for LinkedIn, your site and press." }],
  estTitle: "What would my headshots cost?",
  base: [
    { id: "std", t: "Standard", d: "One look, 1 finished photo", p: 150 },
    { id: "more", t: "More looks", d: "2 outfits, 5 finished photos", p: 350 },
    { id: "pb", t: "Personal branding", d: "A broader gallery, more creative", p: 550, plus: true },
  ],
  extras: [
    { id: "phone", t: "Phone content day", d: "Short videos to go with your photos", p: 350 },
    { id: "page", t: "A one-page site", d: "A simple page to send people to", p: 250, plus: true },
  ],
  prep: [
    { t: "Where it will be used", d: "LinkedIn, website, press or all three." },
    { t: "2 outfits", d: "Solid colors, nothing too busy." },
    { t: "Hair and makeup plan", d: "Done the way you usually wear it." },
    { t: "Glasses or not", d: "Bring them if you wear them every day." },
    { t: "A headshot you like", d: "From anyone, so I know the feeling." },
  ],
  guideTitle: "What makes a headshot work.",
  guide: [
    { t: "Eyes in focus", d: "The sharpest part of the photo should be your eyes.", slot: "A close crop showing sharp eyes" },
    { t: "A real expression", d: "Relaxed and approachable beats a forced smile.", slot: "Forced smile vs. real smile" },
    { t: "A simple background", d: "Nothing that pulls attention away from you.", slot: "Busy background vs. clean background" },
    { t: "Looks like you today", d: "Update it when your look changes.", slot: "An old headshot next to a new one" },
    { t: "Cropped for where it goes", d: "Square for profiles, wider for websites.", slot: "One headshot cropped three ways" },
  ],
};

export const VIDEO: HelpCfg = {
  reel: "A 30 second reel of videos I've made",
  need: "Video / Moving Image",
  noun: "Video",
  videos: [
    { t: "60 seconds: why video works", d: "People stop scrolling for movement." },
    { t: "Behind the scenes of a content day", d: "How we get weeks of clips in one day." },
    { t: "Phone video vs. camera video", d: "Which one you actually need." },
  ],
  forWho: [
    { t: "No video at all", d: "You know you need Reels but never have time." },
    { t: "Videos that don't look like you", d: "Shaky, dark, or off-brand." },
    { t: "A launch or a big moment", d: "A commercial, a release or an opening." },
  ],
  gallery: [
    { label: "A Reel, vertical", kind: "video" },
    { label: "A still from a brand film", kind: "video" },
    { label: "A behind the scenes clip", kind: "video" },
    { label: "A short commercial", kind: "video" },
  ],
  quoteWho: "a video client",
  madeImg: "/assets/work/hero-hana-01.jpg",
  madeTitle: "Planned before we press record.",
  madeP: "Every video starts with a plan: the hook, the shots and where it will be posted. So you leave with clips that actually get used, not a folder you never open.",
  bts: ["Filming on a phone gimbal", "Planning shots on paper", "Editing on the timeline"],
  timeline: [CALL, PLAN, { when: "Before", t: "Shot plan", d: "Hooks, shots and captions, planned around where they'll be posted." }, { when: "Shoot day", t: "Filming", d: "Phone or camera, directed so you don't have to think about it." }, { when: "After", t: "Edits", d: "Cut, captioned and sized for each platform." }],
  estTitle: "What would my video cost?",
  base: [
    { id: "phone", t: "Phone content day", d: "Short videos for Reels and TikTok", p: 350 },
    { id: "cam", t: "Camera video", d: "60 to 90 seconds + vertical cuts", p: 1000, plus: true },
    { id: "film", t: "Brand film or commercial", d: "Planned, shot and edited", p: 1500, plus: true },
  ],
  extras: [
    { id: "shoot", t: "Brand photos", d: "Half day, 30+ edited photos", p: 550, plus: true },
    { id: "canva", t: "Canva template pack", d: "Templates for covers and stories", p: 300, plus: true },
  ],
  prep: [
    { t: "Where the videos will live", d: "Instagram, TikTok, your website, ads." },
    { t: "3 videos you love", d: "From any account. Saved Reels are perfect." },
    { t: "What you want people to do", d: "Book, buy, follow, visit." },
    { t: "Your space ready", d: "Tidy and well lit. I'll help with the rest." },
    { t: "Who's on camera", d: "You, your team, or just your hands and product." },
  ],
  guideTitle: "What makes a short video work.",
  guide: [
    { t: "A hook in 2 seconds", d: "The first moment decides if anyone keeps watching.", slot: "Two openings for the same video" },
    { t: "Made for sound off", d: "Captions, so it works on mute.", slot: "A Reel with clean captions" },
    { t: "Vertical first", d: "Filmed for phones, not cropped down later.", slot: "A vertical frame vs. a cropped one" },
    { t: "One idea per video", d: "Short and clear beats long and packed.", slot: "One clear idea in 15 seconds" },
    { t: "A clear next step", d: "Book, visit, follow. Say it at the end.", slot: "The ending frame with a call to action" },
  ],
  words: [
    { w: "Reel", d: "A short vertical video on Instagram." },
    { w: "Hook", d: "The first second or two that makes people stop scrolling." },
    { w: "B-roll", d: "Extra footage of details and action, used between main shots." },
    { w: "Cut", d: "One edited version of a video, like a 15 or 30 second cut." },
    { w: "Vertical / 9:16", d: "The tall shape that fills a phone screen." },
    { w: "Captions", d: "Words on screen, so it works without sound." },
    { w: "Content day", d: "One day of filming that gives you lots of short clips." },
    { w: "Brand film", d: "A longer, cinematic video about who you are." },
  ],
};

export const DIRECTION: HelpCfg = {
  reel: "A 30 second reel of shoots and content",
  get: [
    { t: "Research + a plan", d: "What to post, when and why." },
    { t: "Templates you approve", d: "Your brand, set up so every post matches." },
    { t: "Photos + short videos", d: "Shot on content days, made for your feed." },
    { t: "Captions", d: "Written in your voice, ready to go." },
    { t: "Files, organized", d: "Everything in Google Drive or Dropbox." },
    { t: "Posted for you", d: "On the Full plan, I handle posting too." },
  ],
  need: "Creative Direction",
  noun: "Content",
  videos: [
    { t: "60 seconds: what creative direction is", d: "The plan behind every shoot and post." },
    { t: "A month of content, planned", d: "From the calendar to the posts." },
    { t: "How monthly content works with me", d: "What you do, what I do." },
  ],
  forWho: [
    { t: "Posting whatever, whenever", d: "No plan, no look, no time." },
    { t: "A shoot with no direction", d: "You hired a photographer but nobody planned it." },
    { t: "Ready to hand it off", d: "You want someone to just take care of it." },
  ],
  gallery: [
    { label: "A month of posts in a grid" },
    { label: "A moodboard for a campaign" },
    { label: "A content calendar" },
    { label: "A campaign shoot, behind the scenes", kind: "video" },
  ],
  quoteWho: "a monthly content client",
  madeImg: "/assets/work/hana-desk-bio.jpg",
  madeTitle: "I plan it, shoot it and hand it over.",
  madeP: "Research, a monthly plan, the shoot and posts ready to go. You approve the templates once, then you just get to post, or I post for you.",
  bts: ["Planning a month on a calendar", "Styling a set before a shoot", "Reviewing posts before they go out"],
  timeline: [CALL, { when: "Week 1", t: "Audit + plan", d: "What's working, what isn't, and a plan for the month." }, { when: "Next", t: "Templates", d: "You approve the look once, so every post matches." }, { when: "Shoot", t: "Content day", d: "Photos and videos for the month, in one go." }, { when: "Monthly", t: "Ready to post", d: "Posts, Reels and captions, handed over or posted for you." }],
  estTitle: "What would my content cost?",
  base: [
    { id: "dir", t: "Shoot direction", d: "Concept, moodboard, shot list and on-set direction", p: 450, plus: true },
    { id: "day", t: "Photo + content day", d: "Shot list, photos, short videos and captions", p: 900, plus: true },
    { id: "camp", t: "Campaign direction", d: "A full campaign, planned and directed", p: 1200, plus: true },
  ],
  extras: [
    { id: "audit", t: "Audit + strategy", d: "Free if you go monthly", p: 400, plus: true },
    { id: "canva", t: "Canva template pack", d: "Your brand in Canva + 15 templates", p: 300, plus: true },
  ],
  prep: [
    { t: "Your logins", d: "Or a plan for who posts. We'll set it up safely." },
    { t: "Your goals", d: "More bookings, more followers, a launch." },
    { t: "3 accounts you love", d: "From anyone, in any industry." },
    { t: "Your brand files", d: "Logo, colors, fonts. No brand yet? We can start there." },
    { t: "What's coming up", d: "Launches, events, sales, holidays." },
  ],
  guideTitle: "What makes a feed work.",
  guide: [
    { t: "A plan, not a scramble", d: "Knowing what you'll post this month takes the stress out.", slot: "A month of posts on a calendar" },
    { t: "A recognizable look", d: "Same colors and templates, so people know it's you.", slot: "A feed that looks like one brand" },
    { t: "Faces", d: "Posts with real people get more love than posts without.", slot: "A post with a face vs. without" },
    { t: "Mix it up", d: "Photos, Reels, carousels and stories each do different jobs.", slot: "One idea as a post, Reel and story" },
    { t: "Consistency", d: "Showing up steadily beats posting a lot then disappearing.", slot: "A steady posting calendar" },
  ],
  words: [
    { w: "Creative direction", d: "The plan for how everything should look and feel." },
    { w: "Content calendar", d: "A schedule of what gets posted and when." },
    { w: "Carousel", d: "A post with several slides people swipe through." },
    { w: "Template", d: "A ready-made design you drop new photos and words into." },
    { w: "Engagement", d: "Likes, comments, shares and saves." },
    { w: "Audit", d: "A look at what's working on your accounts and what isn't." },
    { w: "Moodboard", d: "A collage of references that shows the feeling." },
    { w: "Retainer", d: "A monthly plan, so the work keeps going." },
  ],
};
