/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivateRouteImport } from './routes/private'
import { Route as MovingImageRouteImport } from './routes/moving-image'
import { Route as LogoIdentityRouteImport } from './routes/logo-identity'
import { Route as HeadshotsRouteImport } from './routes/headshots'
import { Route as CreativeDirectionContentRouteImport } from './routes/creative-direction-content'
import { Route as CreativeDirectionRouteImport } from './routes/creative-direction'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotographyIndexRouteImport } from './routes/photography/index'
import { Route as PhotographyPeopleRouteImport } from './routes/photography/people'
import { Route as PhotographyEventsRouteImport } from './routes/photography/events'
import { Route as PhotographyCreativeRouteImport } from './routes/photography/creative'
import { Route as PhotographyBrandsRouteImport } from './routes/photography/brands'
import { Route as CampaignsTheIssueRouteImport } from './routes/campaigns/the-issue'
import { Route as CampaignsStillDifferentRouteImport } from './routes/campaigns/still-different'
import { Route as CampaignsSoniqreignRouteImport } from './routes/campaigns/soniqreign'
import { Route as CampaignsRockstarFlacoRouteImport } from './routes/campaigns/rockstar-flaco'
import { Route as CampaignsReelclipRouteImport } from './routes/campaigns/reelclip'
import { Route as CampaignsParadiceRouteImport } from './routes/campaigns/paradice'
import { Route as CampaignsLeonThomasRouteImport } from './routes/campaigns/leon-thomas'
import { Route as CampaignsKenshiKillzRouteImport } from './routes/campaigns/kenshi-killz'
import { Route as CampaignsJazminsEventsRouteImport } from './routes/campaigns/jazmins-events'
import { Route as CampaignsJaydynFRouteImport } from './routes/campaigns/jaydyn-f'
import { Route as CampaignsHighwayRouteImport } from './routes/campaigns/highway'
import { Route as CampaignsGreenGrillzRouteImport } from './routes/campaigns/green-grillz'
import { Route as CampaignsExhibitionRouteImport } from './routes/campaigns/exhibition'
import { Route as CampaignsEssentialBrowsStudioRouteImport } from './routes/campaigns/essential-brows-studio'
import { Route as CampaignsDjWzrdRouteImport } from './routes/campaigns/dj-wzrd'
import { Route as CampaignsDjPrashantHiyuRouteImport } from './routes/campaigns/dj-prashant-hiyu'
import { Route as CampaignsChutneysRouteImport } from './routes/campaigns/chutneys'
import { Route as CampaignsChitosRouteImport } from './routes/campaigns/chitos'
import { Route as CampaignsBigBabyGucciRouteImport } from './routes/campaigns/big-baby-gucci'
import { Route as CampaignsBarBistroRouteImport } from './routes/campaigns/bar-bistro'
import { Route as CampaignsAveryTienRouteImport } from './routes/campaigns/avery-tien'
import { Route as CampaignsAngieTiaraBeautyRouteImport } from './routes/campaigns/angie-tiara-beauty'
import { Route as ArchiveSplatRouteImport } from './routes/archive/$'

const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingImageRoute = MovingImageRouteImport.update({
  id: '/moving-image',
  path: '/moving-image',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoIdentityRoute = LogoIdentityRouteImport.update({
  id: '/logo-identity',
  path: '/logo-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadshotsRoute = HeadshotsRouteImport.update({
  id: '/headshots',
  path: '/headshots',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeDirectionContentRoute =
  CreativeDirectionContentRouteImport.update({
    id: '/creative-direction-content',
    path: '/creative-direction-content',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreativeDirectionRoute = CreativeDirectionRouteImport.update({
  id: '/creative-direction',
  path: '/creative-direction',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyIndexRoute = PhotographyIndexRouteImport.update({
  id: '/photography/',
  path: '/photography/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyPeopleRoute = PhotographyPeopleRouteImport.update({
  id: '/photography/people',
  path: '/photography/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyEventsRoute = PhotographyEventsRouteImport.update({
  id: '/photography/events',
  path: '/photography/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyCreativeRoute = PhotographyCreativeRouteImport.update({
  id: '/photography/creative',
  path: '/photography/creative',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyBrandsRoute = PhotographyBrandsRouteImport.update({
  id: '/photography/brands',
  path: '/photography/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsTheIssueRoute = CampaignsTheIssueRouteImport.update({
  id: '/campaigns/the-issue',
  path: '/campaigns/the-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsStillDifferentRoute = CampaignsStillDifferentRouteImport.update({
  id: '/campaigns/still-different',
  path: '/campaigns/still-different',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSoniqreignRoute = CampaignsSoniqreignRouteImport.update({
  id: '/campaigns/soniqreign',
  path: '/campaigns/soniqreign',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRockstarFlacoRoute = CampaignsRockstarFlacoRouteImport.update({
  id: '/campaigns/rockstar-flaco',
  path: '/campaigns/rockstar-flaco',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsReelclipRoute = CampaignsReelclipRouteImport.update({
  id: '/campaigns/reelclip',
  path: '/campaigns/reelclip',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsParadiceRoute = CampaignsParadiceRouteImport.update({
  id: '/campaigns/paradice',
  path: '/campaigns/paradice',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsLeonThomasRoute = CampaignsLeonThomasRouteImport.update({
  id: '/campaigns/leon-thomas',
  path: '/campaigns/leon-thomas',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsKenshiKillzRoute = CampaignsKenshiKillzRouteImport.update({
  id: '/campaigns/kenshi-killz',
  path: '/campaigns/kenshi-killz',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsJazminsEventsRoute = CampaignsJazminsEventsRouteImport.update({
  id: '/campaigns/jazmins-events',
  path: '/campaigns/jazmins-events',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsJaydynFRoute = CampaignsJaydynFRouteImport.update({
  id: '/campaigns/jaydyn-f',
  path: '/campaigns/jaydyn-f',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsHighwayRoute = CampaignsHighwayRouteImport.update({
  id: '/campaigns/highway',
  path: '/campaigns/highway',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsGreenGrillzRoute = CampaignsGreenGrillzRouteImport.update({
  id: '/campaigns/green-grillz',
  path: '/campaigns/green-grillz',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsExhibitionRoute = CampaignsExhibitionRouteImport.update({
  id: '/campaigns/exhibition',
  path: '/campaigns/exhibition',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsEssentialBrowsStudioRoute =
  CampaignsEssentialBrowsStudioRouteImport.update({
    id: '/campaigns/essential-brows-studio',
    path: '/campaigns/essential-brows-studio',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsDjWzrdRoute = CampaignsDjWzrdRouteImport.update({
  id: '/campaigns/dj-wzrd',
  path: '/campaigns/dj-wzrd',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsDjPrashantHiyuRoute = CampaignsDjPrashantHiyuRouteImport.update({
  id: '/campaigns/dj-prashant-hiyu',
  path: '/campaigns/dj-prashant-hiyu',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsChutneysRoute = CampaignsChutneysRouteImport.update({
  id: '/campaigns/chutneys',
  path: '/campaigns/chutneys',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsChitosRoute = CampaignsChitosRouteImport.update({
  id: '/campaigns/chitos',
  path: '/campaigns/chitos',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsBigBabyGucciRoute = CampaignsBigBabyGucciRouteImport.update({
  id: '/campaigns/big-baby-gucci',
  path: '/campaigns/big-baby-gucci',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsBarBistroRoute = CampaignsBarBistroRouteImport.update({
  id: '/campaigns/bar-bistro',
  path: '/campaigns/bar-bistro',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsAveryTienRoute = CampaignsAveryTienRouteImport.update({
  id: '/campaigns/avery-tien',
  path: '/campaigns/avery-tien',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsAngieTiaraBeautyRoute =
  CampaignsAngieTiaraBeautyRouteImport.update({
    id: '/campaigns/angie-tiara-beauty',
    path: '/campaigns/angie-tiara-beauty',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchiveSplatRoute = ArchiveSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ArchiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/branding': typeof BrandingRoute
  '/creative-direction': typeof CreativeDirectionRoute
  '/creative-direction-content': typeof CreativeDirectionContentRoute
  '/headshots': typeof HeadshotsRoute
  '/logo-identity': typeof LogoIdentityRoute
  '/moving-image': typeof MovingImageRoute
  '/private': typeof PrivateRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/websites': typeof WebsitesRoute
  '/archive/$': typeof ArchiveSplatRoute
  '/campaigns/angie-tiara-beauty': typeof CampaignsAngieTiaraBeautyRoute
  '/campaigns/avery-tien': typeof CampaignsAveryTienRoute
  '/campaigns/bar-bistro': typeof CampaignsBarBistroRoute
  '/campaigns/big-baby-gucci': typeof CampaignsBigBabyGucciRoute
  '/campaigns/chitos': typeof CampaignsChitosRoute
  '/campaigns/chutneys': typeof CampaignsChutneysRoute
  '/campaigns/dj-prashant-hiyu': typeof CampaignsDjPrashantHiyuRoute
  '/campaigns/dj-wzrd': typeof CampaignsDjWzrdRoute
  '/campaigns/essential-brows-studio': typeof CampaignsEssentialBrowsStudioRoute
  '/campaigns/exhibition': typeof CampaignsExhibitionRoute
  '/campaigns/green-grillz': typeof CampaignsGreenGrillzRoute
  '/campaigns/highway': typeof CampaignsHighwayRoute
  '/campaigns/jaydyn-f': typeof CampaignsJaydynFRoute
  '/campaigns/jazmins-events': typeof CampaignsJazminsEventsRoute
  '/campaigns/kenshi-killz': typeof CampaignsKenshiKillzRoute
  '/campaigns/leon-thomas': typeof CampaignsLeonThomasRoute
  '/campaigns/paradice': typeof CampaignsParadiceRoute
  '/campaigns/reelclip': typeof CampaignsReelclipRoute
  '/campaigns/rockstar-flaco': typeof CampaignsRockstarFlacoRoute
  '/campaigns/soniqreign': typeof CampaignsSoniqreignRoute
  '/campaigns/still-different': typeof CampaignsStillDifferentRoute
  '/campaigns/the-issue': typeof CampaignsTheIssueRoute
  '/photography/brands': typeof PhotographyBrandsRoute
  '/photography/creative': typeof PhotographyCreativeRoute
  '/photography/events': typeof PhotographyEventsRoute
  '/photography/people': typeof PhotographyPeopleRoute
  '/photography/': typeof PhotographyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/branding': typeof BrandingRoute
  '/creative-direction': typeof CreativeDirectionRoute
  '/creative-direction-content': typeof CreativeDirectionContentRoute
  '/headshots': typeof HeadshotsRoute
  '/logo-identity': typeof LogoIdentityRoute
  '/moving-image': typeof MovingImageRoute
  '/private': typeof PrivateRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/websites': typeof WebsitesRoute
  '/archive/$': typeof ArchiveSplatRoute
  '/campaigns/angie-tiara-beauty': typeof CampaignsAngieTiaraBeautyRoute
  '/campaigns/avery-tien': typeof CampaignsAveryTienRoute
  '/campaigns/bar-bistro': typeof CampaignsBarBistroRoute
  '/campaigns/big-baby-gucci': typeof CampaignsBigBabyGucciRoute
  '/campaigns/chitos': typeof CampaignsChitosRoute
  '/campaigns/chutneys': typeof CampaignsChutneysRoute
  '/campaigns/dj-prashant-hiyu': typeof CampaignsDjPrashantHiyuRoute
  '/campaigns/dj-wzrd': typeof CampaignsDjWzrdRoute
  '/campaigns/essential-brows-studio': typeof CampaignsEssentialBrowsStudioRoute
  '/campaigns/exhibition': typeof CampaignsExhibitionRoute
  '/campaigns/green-grillz': typeof CampaignsGreenGrillzRoute
  '/campaigns/highway': typeof CampaignsHighwayRoute
  '/campaigns/jaydyn-f': typeof CampaignsJaydynFRoute
  '/campaigns/jazmins-events': typeof CampaignsJazminsEventsRoute
  '/campaigns/kenshi-killz': typeof CampaignsKenshiKillzRoute
  '/campaigns/leon-thomas': typeof CampaignsLeonThomasRoute
  '/campaigns/paradice': typeof CampaignsParadiceRoute
  '/campaigns/reelclip': typeof CampaignsReelclipRoute
  '/campaigns/rockstar-flaco': typeof CampaignsRockstarFlacoRoute
  '/campaigns/soniqreign': typeof CampaignsSoniqreignRoute
  '/campaigns/still-different': typeof CampaignsStillDifferentRoute
  '/campaigns/the-issue': typeof CampaignsTheIssueRoute
  '/photography/brands': typeof PhotographyBrandsRoute
  '/photography/creative': typeof PhotographyCreativeRoute
  '/photography/events': typeof PhotographyEventsRoute
  '/photography/people': typeof PhotographyPeopleRoute
  '/photography': typeof PhotographyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/branding': typeof BrandingRoute
  '/creative-direction': typeof CreativeDirectionRoute
  '/creative-direction-content': typeof CreativeDirectionContentRoute
  '/headshots': typeof HeadshotsRoute
  '/logo-identity': typeof LogoIdentityRoute
  '/moving-image': typeof MovingImageRoute
  '/private': typeof PrivateRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/websites': typeof WebsitesRoute
  '/archive/$': typeof ArchiveSplatRoute
  '/campaigns/angie-tiara-beauty': typeof CampaignsAngieTiaraBeautyRoute
  '/campaigns/avery-tien': typeof CampaignsAveryTienRoute
  '/campaigns/bar-bistro': typeof CampaignsBarBistroRoute
  '/campaigns/big-baby-gucci': typeof CampaignsBigBabyGucciRoute
  '/campaigns/chitos': typeof CampaignsChitosRoute
  '/campaigns/chutneys': typeof CampaignsChutneysRoute
  '/campaigns/dj-prashant-hiyu': typeof CampaignsDjPrashantHiyuRoute
  '/campaigns/dj-wzrd': typeof CampaignsDjWzrdRoute
  '/campaigns/essential-brows-studio': typeof CampaignsEssentialBrowsStudioRoute
  '/campaigns/exhibition': typeof CampaignsExhibitionRoute
  '/campaigns/green-grillz': typeof CampaignsGreenGrillzRoute
  '/campaigns/highway': typeof CampaignsHighwayRoute
  '/campaigns/jaydyn-f': typeof CampaignsJaydynFRoute
  '/campaigns/jazmins-events': typeof CampaignsJazminsEventsRoute
  '/campaigns/kenshi-killz': typeof CampaignsKenshiKillzRoute
  '/campaigns/leon-thomas': typeof CampaignsLeonThomasRoute
  '/campaigns/paradice': typeof CampaignsParadiceRoute
  '/campaigns/reelclip': typeof CampaignsReelclipRoute
  '/campaigns/rockstar-flaco': typeof CampaignsRockstarFlacoRoute
  '/campaigns/soniqreign': typeof CampaignsSoniqreignRoute
  '/campaigns/still-different': typeof CampaignsStillDifferentRoute
  '/campaigns/the-issue': typeof CampaignsTheIssueRoute
  '/photography/brands': typeof PhotographyBrandsRoute
  '/photography/creative': typeof PhotographyCreativeRoute
  '/photography/events': typeof PhotographyEventsRoute
  '/photography/people': typeof PhotographyPeopleRoute
  '/photography/': typeof PhotographyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/branding'
    | '/creative-direction'
    | '/creative-direction-content'
    | '/headshots'
    | '/logo-identity'
    | '/moving-image'
    | '/private'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/websites'
    | '/archive/$'
    | '/campaigns/angie-tiara-beauty'
    | '/campaigns/avery-tien'
    | '/campaigns/bar-bistro'
    | '/campaigns/big-baby-gucci'
    | '/campaigns/chitos'
    | '/campaigns/chutneys'
    | '/campaigns/dj-prashant-hiyu'
    | '/campaigns/dj-wzrd'
    | '/campaigns/essential-brows-studio'
    | '/campaigns/exhibition'
    | '/campaigns/green-grillz'
    | '/campaigns/highway'
    | '/campaigns/jaydyn-f'
    | '/campaigns/jazmins-events'
    | '/campaigns/kenshi-killz'
    | '/campaigns/leon-thomas'
    | '/campaigns/paradice'
    | '/campaigns/reelclip'
    | '/campaigns/rockstar-flaco'
    | '/campaigns/soniqreign'
    | '/campaigns/still-different'
    | '/campaigns/the-issue'
    | '/photography/brands'
    | '/photography/creative'
    | '/photography/events'
    | '/photography/people'
    | '/photography/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/branding'
    | '/creative-direction'
    | '/creative-direction-content'
    | '/headshots'
    | '/logo-identity'
    | '/moving-image'
    | '/private'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/websites'
    | '/archive/$'
    | '/campaigns/angie-tiara-beauty'
    | '/campaigns/avery-tien'
    | '/campaigns/bar-bistro'
    | '/campaigns/big-baby-gucci'
    | '/campaigns/chitos'
    | '/campaigns/chutneys'
    | '/campaigns/dj-prashant-hiyu'
    | '/campaigns/dj-wzrd'
    | '/campaigns/essential-brows-studio'
    | '/campaigns/exhibition'
    | '/campaigns/green-grillz'
    | '/campaigns/highway'
    | '/campaigns/jaydyn-f'
    | '/campaigns/jazmins-events'
    | '/campaigns/kenshi-killz'
    | '/campaigns/leon-thomas'
    | '/campaigns/paradice'
    | '/campaigns/reelclip'
    | '/campaigns/rockstar-flaco'
    | '/campaigns/soniqreign'
    | '/campaigns/still-different'
    | '/campaigns/the-issue'
    | '/photography/brands'
    | '/photography/creative'
    | '/photography/events'
    | '/photography/people'
    | '/photography'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/branding'
    | '/creative-direction'
    | '/creative-direction-content'
    | '/headshots'
    | '/logo-identity'
    | '/moving-image'
    | '/private'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/websites'
    | '/archive/$'
    | '/campaigns/angie-tiara-beauty'
    | '/campaigns/avery-tien'
    | '/campaigns/bar-bistro'
    | '/campaigns/big-baby-gucci'
    | '/campaigns/chitos'
    | '/campaigns/chutneys'
    | '/campaigns/dj-prashant-hiyu'
    | '/campaigns/dj-wzrd'
    | '/campaigns/essential-brows-studio'
    | '/campaigns/exhibition'
    | '/campaigns/green-grillz'
    | '/campaigns/highway'
    | '/campaigns/jaydyn-f'
    | '/campaigns/jazmins-events'
    | '/campaigns/kenshi-killz'
    | '/campaigns/leon-thomas'
    | '/campaigns/paradice'
    | '/campaigns/reelclip'
    | '/campaigns/rockstar-flaco'
    | '/campaigns/soniqreign'
    | '/campaigns/still-different'
    | '/campaigns/the-issue'
    | '/photography/brands'
    | '/photography/creative'
    | '/photography/events'
    | '/photography/people'
    | '/photography/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  BrandingRoute: typeof BrandingRoute
  CreativeDirectionRoute: typeof CreativeDirectionRoute
  CreativeDirectionContentRoute: typeof CreativeDirectionContentRoute
  HeadshotsRoute: typeof HeadshotsRoute
  LogoIdentityRoute: typeof LogoIdentityRoute
  MovingImageRoute: typeof MovingImageRoute
  PrivateRoute: typeof PrivateRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WebsitesRoute: typeof WebsitesRoute
  CampaignsAngieTiaraBeautyRoute: typeof CampaignsAngieTiaraBeautyRoute
  CampaignsAveryTienRoute: typeof CampaignsAveryTienRoute
  CampaignsBarBistroRoute: typeof CampaignsBarBistroRoute
  CampaignsBigBabyGucciRoute: typeof CampaignsBigBabyGucciRoute
  CampaignsChitosRoute: typeof CampaignsChitosRoute
  CampaignsChutneysRoute: typeof CampaignsChutneysRoute
  CampaignsDjPrashantHiyuRoute: typeof CampaignsDjPrashantHiyuRoute
  CampaignsDjWzrdRoute: typeof CampaignsDjWzrdRoute
  CampaignsEssentialBrowsStudioRoute: typeof CampaignsEssentialBrowsStudioRoute
  CampaignsExhibitionRoute: typeof CampaignsExhibitionRoute
  CampaignsGreenGrillzRoute: typeof CampaignsGreenGrillzRoute
  CampaignsHighwayRoute: typeof CampaignsHighwayRoute
  CampaignsJaydynFRoute: typeof CampaignsJaydynFRoute
  CampaignsJazminsEventsRoute: typeof CampaignsJazminsEventsRoute
  CampaignsKenshiKillzRoute: typeof CampaignsKenshiKillzRoute
  CampaignsLeonThomasRoute: typeof CampaignsLeonThomasRoute
  CampaignsParadiceRoute: typeof CampaignsParadiceRoute
  CampaignsReelclipRoute: typeof CampaignsReelclipRoute
  CampaignsRockstarFlacoRoute: typeof CampaignsRockstarFlacoRoute
  CampaignsSoniqreignRoute: typeof CampaignsSoniqreignRoute
  CampaignsStillDifferentRoute: typeof CampaignsStillDifferentRoute
  CampaignsTheIssueRoute: typeof CampaignsTheIssueRoute
  PhotographyBrandsRoute: typeof PhotographyBrandsRoute
  PhotographyCreativeRoute: typeof PhotographyCreativeRoute
  PhotographyEventsRoute: typeof PhotographyEventsRoute
  PhotographyPeopleRoute: typeof PhotographyPeopleRoute
  PhotographyIndexRoute: typeof PhotographyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private': {
      id: '/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-image': {
      id: '/moving-image'
      path: '/moving-image'
      fullPath: '/moving-image'
      preLoaderRoute: typeof MovingImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-identity': {
      id: '/logo-identity'
      path: '/logo-identity'
      fullPath: '/logo-identity'
      preLoaderRoute: typeof LogoIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headshots': {
      id: '/headshots'
      path: '/headshots'
      fullPath: '/headshots'
      preLoaderRoute: typeof HeadshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-direction-content': {
      id: '/creative-direction-content'
      path: '/creative-direction-content'
      fullPath: '/creative-direction-content'
      preLoaderRoute: typeof CreativeDirectionContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-direction': {
      id: '/creative-direction'
      path: '/creative-direction'
      fullPath: '/creative-direction'
      preLoaderRoute: typeof CreativeDirectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/': {
      id: '/photography/'
      path: '/photography'
      fullPath: '/photography/'
      preLoaderRoute: typeof PhotographyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/people': {
      id: '/photography/people'
      path: '/photography/people'
      fullPath: '/photography/people'
      preLoaderRoute: typeof PhotographyPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/events': {
      id: '/photography/events'
      path: '/photography/events'
      fullPath: '/photography/events'
      preLoaderRoute: typeof PhotographyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/creative': {
      id: '/photography/creative'
      path: '/photography/creative'
      fullPath: '/photography/creative'
      preLoaderRoute: typeof PhotographyCreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/brands': {
      id: '/photography/brands'
      path: '/photography/brands'
      fullPath: '/photography/brands'
      preLoaderRoute: typeof PhotographyBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/the-issue': {
      id: '/campaigns/the-issue'
      path: '/campaigns/the-issue'
      fullPath: '/campaigns/the-issue'
      preLoaderRoute: typeof CampaignsTheIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/still-different': {
      id: '/campaigns/still-different'
      path: '/campaigns/still-different'
      fullPath: '/campaigns/still-different'
      preLoaderRoute: typeof CampaignsStillDifferentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/soniqreign': {
      id: '/campaigns/soniqreign'
      path: '/campaigns/soniqreign'
      fullPath: '/campaigns/soniqreign'
      preLoaderRoute: typeof CampaignsSoniqreignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/rockstar-flaco': {
      id: '/campaigns/rockstar-flaco'
      path: '/campaigns/rockstar-flaco'
      fullPath: '/campaigns/rockstar-flaco'
      preLoaderRoute: typeof CampaignsRockstarFlacoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/reelclip': {
      id: '/campaigns/reelclip'
      path: '/campaigns/reelclip'
      fullPath: '/campaigns/reelclip'
      preLoaderRoute: typeof CampaignsReelclipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/paradice': {
      id: '/campaigns/paradice'
      path: '/campaigns/paradice'
      fullPath: '/campaigns/paradice'
      preLoaderRoute: typeof CampaignsParadiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/leon-thomas': {
      id: '/campaigns/leon-thomas'
      path: '/campaigns/leon-thomas'
      fullPath: '/campaigns/leon-thomas'
      preLoaderRoute: typeof CampaignsLeonThomasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/kenshi-killz': {
      id: '/campaigns/kenshi-killz'
      path: '/campaigns/kenshi-killz'
      fullPath: '/campaigns/kenshi-killz'
      preLoaderRoute: typeof CampaignsKenshiKillzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/jazmins-events': {
      id: '/campaigns/jazmins-events'
      path: '/campaigns/jazmins-events'
      fullPath: '/campaigns/jazmins-events'
      preLoaderRoute: typeof CampaignsJazminsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/jaydyn-f': {
      id: '/campaigns/jaydyn-f'
      path: '/campaigns/jaydyn-f'
      fullPath: '/campaigns/jaydyn-f'
      preLoaderRoute: typeof CampaignsJaydynFRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/highway': {
      id: '/campaigns/highway'
      path: '/campaigns/highway'
      fullPath: '/campaigns/highway'
      preLoaderRoute: typeof CampaignsHighwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/green-grillz': {
      id: '/campaigns/green-grillz'
      path: '/campaigns/green-grillz'
      fullPath: '/campaigns/green-grillz'
      preLoaderRoute: typeof CampaignsGreenGrillzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/exhibition': {
      id: '/campaigns/exhibition'
      path: '/campaigns/exhibition'
      fullPath: '/campaigns/exhibition'
      preLoaderRoute: typeof CampaignsExhibitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/essential-brows-studio': {
      id: '/campaigns/essential-brows-studio'
      path: '/campaigns/essential-brows-studio'
      fullPath: '/campaigns/essential-brows-studio'
      preLoaderRoute: typeof CampaignsEssentialBrowsStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/dj-wzrd': {
      id: '/campaigns/dj-wzrd'
      path: '/campaigns/dj-wzrd'
      fullPath: '/campaigns/dj-wzrd'
      preLoaderRoute: typeof CampaignsDjWzrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/dj-prashant-hiyu': {
      id: '/campaigns/dj-prashant-hiyu'
      path: '/campaigns/dj-prashant-hiyu'
      fullPath: '/campaigns/dj-prashant-hiyu'
      preLoaderRoute: typeof CampaignsDjPrashantHiyuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/chutneys': {
      id: '/campaigns/chutneys'
      path: '/campaigns/chutneys'
      fullPath: '/campaigns/chutneys'
      preLoaderRoute: typeof CampaignsChutneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/chitos': {
      id: '/campaigns/chitos'
      path: '/campaigns/chitos'
      fullPath: '/campaigns/chitos'
      preLoaderRoute: typeof CampaignsChitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/big-baby-gucci': {
      id: '/campaigns/big-baby-gucci'
      path: '/campaigns/big-baby-gucci'
      fullPath: '/campaigns/big-baby-gucci'
      preLoaderRoute: typeof CampaignsBigBabyGucciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/bar-bistro': {
      id: '/campaigns/bar-bistro'
      path: '/campaigns/bar-bistro'
      fullPath: '/campaigns/bar-bistro'
      preLoaderRoute: typeof CampaignsBarBistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/avery-tien': {
      id: '/campaigns/avery-tien'
      path: '/campaigns/avery-tien'
      fullPath: '/campaigns/avery-tien'
      preLoaderRoute: typeof CampaignsAveryTienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/angie-tiara-beauty': {
      id: '/campaigns/angie-tiara-beauty'
      path: '/campaigns/angie-tiara-beauty'
      fullPath: '/campaigns/angie-tiara-beauty'
      preLoaderRoute: typeof CampaignsAngieTiaraBeautyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$': {
      id: '/archive/$'
      path: '/$'
      fullPath: '/archive/$'
      preLoaderRoute: typeof ArchiveSplatRouteImport
      parentRoute: typeof ArchiveRoute
    }
  }
}

interface ArchiveRouteChildren {
  ArchiveSplatRoute: typeof ArchiveSplatRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveSplatRoute: ArchiveSplatRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  BrandingRoute: BrandingRoute,
  CreativeDirectionRoute: CreativeDirectionRoute,
  CreativeDirectionContentRoute: CreativeDirectionContentRoute,
  HeadshotsRoute: HeadshotsRoute,
  LogoIdentityRoute: LogoIdentityRoute,
  MovingImageRoute: MovingImageRoute,
  PrivateRoute: PrivateRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WebsitesRoute: WebsitesRoute,
  CampaignsAngieTiaraBeautyRoute: CampaignsAngieTiaraBeautyRoute,
  CampaignsAveryTienRoute: CampaignsAveryTienRoute,
  CampaignsBarBistroRoute: CampaignsBarBistroRoute,
  CampaignsBigBabyGucciRoute: CampaignsBigBabyGucciRoute,
  CampaignsChitosRoute: CampaignsChitosRoute,
  CampaignsChutneysRoute: CampaignsChutneysRoute,
  CampaignsDjPrashantHiyuRoute: CampaignsDjPrashantHiyuRoute,
  CampaignsDjWzrdRoute: CampaignsDjWzrdRoute,
  CampaignsEssentialBrowsStudioRoute: CampaignsEssentialBrowsStudioRoute,
  CampaignsExhibitionRoute: CampaignsExhibitionRoute,
  CampaignsGreenGrillzRoute: CampaignsGreenGrillzRoute,
  CampaignsHighwayRoute: CampaignsHighwayRoute,
  CampaignsJaydynFRoute: CampaignsJaydynFRoute,
  CampaignsJazminsEventsRoute: CampaignsJazminsEventsRoute,
  CampaignsKenshiKillzRoute: CampaignsKenshiKillzRoute,
  CampaignsLeonThomasRoute: CampaignsLeonThomasRoute,
  CampaignsParadiceRoute: CampaignsParadiceRoute,
  CampaignsReelclipRoute: CampaignsReelclipRoute,
  CampaignsRockstarFlacoRoute: CampaignsRockstarFlacoRoute,
  CampaignsSoniqreignRoute: CampaignsSoniqreignRoute,
  CampaignsStillDifferentRoute: CampaignsStillDifferentRoute,
  CampaignsTheIssueRoute: CampaignsTheIssueRoute,
  PhotographyBrandsRoute: PhotographyBrandsRoute,
  PhotographyCreativeRoute: PhotographyCreativeRoute,
  PhotographyEventsRoute: PhotographyEventsRoute,
  PhotographyPeopleRoute: PhotographyPeopleRoute,
  PhotographyIndexRoute: PhotographyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
